name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
  schedule:
    - cron: '0 12 15 * *'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4

      - run: docker build --target dev -t nre-feed-parser:dev .
        env:
          DOCKER_BUILDKIT: 1

      - run: |
          docker run --rm -t \
            --entrypoint pest \
            nre-feed-parser:dev

# vim: sw=2 ts=2
